# Generated by Django 4.2.7 on 2023-11-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_cart_options_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='carrinhos', to='loja.produto'),
        ),
    ]
